version: "3.9"

services:
  api:
    build: ./api
    container_name: notification-api
    ports:
    - 5000:5000
    env_file: ./api/.env
  
  email-worker:
    build: ./email-worker
    container_name: email-worker
    env_file: ./email-worker/.env
    volumes:
    - ./email-worker:/app

  sms-worker:
    build: ./sms-worker
    container_name: sms-worker
    env_file: ./sms-worker/.env