version: "3.9"

services:
  api:
    build: .
    container_name: notification-api
    ports:
    - 5000:5000
    environment:
    - MONGO_URI=${MONGO_URI}
    - REDIS_URL=${REDIS_URL}
    volumes:
    - .:/app
    depends_on:
    - mongo
    - redis
  
  email-worker:
    build: .
    container_name: email-worker
    command: node worker/emailWorker.js
    environment:
    - MONGO_URI=${MONGO_URI}
    - REDIS_URL=${REDIS_URL}
    - EMAIL_USER=${EMAIL_USER}
    - EMAIL_PASS=${EMAIL_PASS}
    volumes:
    - .:/app
    depends_on:
    - mongo
    - redis

  sms-worker:
    build: .
    container_name: sms-worker
    command: node worker/smsWorker.js
    environment:
    - MONGO_URI=${MONGO_URI}
    - REDIS_URL=${REDIS_URL}
    - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
    - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    - TWILIO_VERIFIED_SID=${TWILIO_VERIFIED_SID}
    volumes:
    - .:/app
    depends_on:
    - mongo
    - redis

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
    - 27017:27017
    volumes:
    - microservices-notification-system:/data/db

  redis:
    image: redis
    container_name: redis-server
    ports:
    - 6379:6379
  
volumes:
  microservices-notification-system:



