version: "3.9"

services:
  api:
    build: .
    container_name: notification-api
    ports:
    - 5000:5000
    environment:
    - MONGO_URI=${MONGO_URI}
    - REDIS_URL=${REDIS_URL}
    volumes:
    - .:/app
    depends_on:
    - mongo
    - redis
  
  worker:
    build: .
    container_name: email-worker
    command: node worker/emailWorker.js
    environment:
    - MONGO_URI=${MONGO_URI}
    - REDIS_URL=${REDIS_URL}
    - EMAIL_USER=${EMAIL_USER}
    - EMAIL_PASS=${EMAIL_PASS}
    volumes:
    - .:/app
    depends_on:
    - mongo
    - redis

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
    - 27017:27017

  redis:
    image: redis
    container_name: redis-server
    ports:
    - 6379:6379



